project:
  type: website
  output-dir: docs

website:
  title: "Evelyn Bermudez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - experience.qmd
      - courses.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

