project:
  type: website
  output-dir: docs

website:
  title: "Evelyn Bermudez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - experience.qmd
      - courses.qmd

format:
  html:
    theme: styles.scss # I've also removed the `css: styles.css` option that was included by default
    toc: true
    page-layout: full

editor: visual

